### ISSUE TITLE
It won't hold the connection to wireguard.

### ISSUE THREAD

**Issue by legomannetje** [bigmoby/addon-wireguard-client#11]
# Problem/Motivation

> When installed in the hassio os version it is unable to connect.

## Expected behavior

> It connects to my wireguard server

## Actual behavior

> It makes an initial connection, but doesn't hold it. I can see it connects, send a couple packages, and then it drops

## Steps to reproduce

> Install hassio os, this plugin and try to connect to a server.

## Proposed changes

No idea.

## Logs
https://pastebin.com/aem09zsr

**Comment by legomannetje** [comment]
interface:
  private_key: PrivateKey
  address: 10.116.181.38
  dns:
    - 10.2.3.1
  post_up: iptables -t nat -A POSTROUTING -o wg0 -j MASQUERADE
  post_down: iptables -t nat -D POSTROUTING -o wg0 -j MASQUERADE
peer:
  public_key: MyPublicKey
  pre_shared_key: PreSharedKey
  endpoint: ServerIP:41775
  allowed_ips:
    - 0.0.0.0/0,::/0
  persistent_keep_alive: '25'

**Comment by bigmoby** [comment]
Hi @legomannetje ,
please try with this configuration:
`interface:
  private_key: PrivateKey
  address: 10.116.181.38
  dns:
    - 10.2.3.1
  post_up: iptables -t nat -A POSTROUTING -o wg0 -j MASQUERADE
  post_down: iptables -t nat -D POSTROUTING -o wg0 -j MASQUERADE
peer:
  public_key: MyPublicKey
  pre_shared_key: PreSharedKey
  endpoint: ServerIP:41775
  allowed_ips:
    - 10.116.181.0/24
  persistent_keep_alive: 25`

I changed `allowed_ips` notation avoiding the 0.0.0.0 (no sense because I could imagine your client is not on the same host machine) neither the IPv6 not supported.
Please try it and give me a feedback 👍
p.s.: Are you sure that your dns is aware of the ServerIP resolution?
